t ?= esp32

TERMINAL_SPEED := 115200

ifeq ($t, esp8266)
BOARD := d1_mini
UPLOAD_SPEED := 921600
FS_DIR := programs
EESZ := 4M1M
F_CPU := 80
CPPFLAGS = -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=PIN_D8 -DTFT_DC=PIN_D1 \
	-DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD \
	-DHARDWARE_H=\"hw/esp8266-pwm-fs-23k256.h\" -DTERMINAL_SPEED=$(TERMINAL_SPEED) -DDEBUGGING=1
LIBRARIES := TFT_eSPI SpiRAM
endif

ifeq ($t, tivac)
BOARD := EK-LM4F120XL
CPPFLAGS := -DDEBUGGING -DHARDWARE_H=\"hw/lm4f-utft-sd.h\" -DTERMINAL_SPEED=$(TERMINAL_SPEED)
LIBRARIES := UTFT SD SpiRAM
endif

ifeq ($t, esp32)
UPLOAD_SPEED := 921600
FS_DIR := programs
CPPFLAGS = -DDEBUGGING -DCPU_DEBUG -DTERMINAL_SPEED=$(TERMINAL_SPEED)
LIBRARIES = FS SPIFFS

ifeq ($b, lilygo)
BOARD := ttgo-t7-v14-mini32
SERIAL_PORT := /dev/ttyACM0
CPPFLAGS += -DHARDWARE_H=\"hw/lilygo-vga32.h\"
LIBRARIES += FabGL WiFi

else
BOARD := node32s
CPPFLAGS += -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=5 -DTFT_DC=2 \
	-DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD \
	-DHARDWARE_H=\"hw/esp32-espi.h\"
LIBRARIES += TFT_eSPI
endif
endif

include $t.mk
