t ?= esp32

TERMINAL_SPEED := 115200
CPPFLAGS = -Wall -DDEBUGGING=0x33 -DTERMINAL_SPEED=$(TERMINAL_SPEED) -DUSE_OWN_KBD -DSIMPLE_TIMER_MICROS
LIBRARIES = PS2KeyAdvanced PS2KeyMap SimpleTimer

ifeq ($t, esp8266)
BOARD := d1_mini
baud := 921600
eesz := 4M1M
CPPFLAGS += -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=PIN_D8 -DTFT_DC=PIN_D1 \
	-DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD \
	-DHARDWARE_H=\"hw/esp8bit.h\"
LIBRARIES += TFT_eSPI SpiRAM LittleFS
endif

ifeq ($t, esp32)
LIBRARIES += FS SPIFFS Network

ifeq ($b, lilygo)
BOARD := ttgo-t7-v14-mini32
SERIAL_PORT := /dev/ttyACM0
CPPFLAGS += -DUSE_SD
LIBRARIES += ESP32Lib SD

else
BOARD := lolin32
CPPFLAGS += -DUSER_SETUP_LOADED -DILI9341_DRIVER -DTFT_CS=5 -DTFT_DC=2 \
	-DTFT_RST=-1 -DSPI_FREQUENCY=40000000 -DLOAD_GLCD \
	-DHARDWARE_H=\"hw/esp32-example.h\" -DUSE_SERIAL
LIBRARIES += TFT_eSPI
endif
endif

ifeq ($t, rp2040)
BOARD := adafruit_feather_dvi
flash := 8388608_2097152
CPPFLAGS += -DUSE_SERIAL
#CPPFLAGS += -DPS2_SERIAL_KBD=\"UK\"
CPPFLAGS += -DDVI_BIT_DEPTH=1 -DDVI_RESOLUTION=DVI_RES_640x240p60
LIBRARIES += LittleFS PicoDVI Adafruit_GFX Adafruit_BusIO Wire
endif

include $t.mk
